server:
  port: 8003

spring:
  datasource:
    first:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://ylnzk.cn:3306/blm?characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: ylnzk3306_
    second:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://112.124.20.197:3306/blm?characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: ylnzk3306_
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:
    name: shop-provider
  registry:
    address: zookeeper://ylnzk.cn:2181
  protocol:
    name: dubbo
    port: 20881

